// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZU4O3wYzl0aA6gHyrBKOtrGfBRzX0618',
    appId: '1:1052600817177:android:d80518ffcdf7aa15073c88',
    messagingSenderId: '1052600817177',
    projectId: 'fanuccontrol-b5699',
    databaseURL: 'https://fanuccontrol-b5699-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fanuccontrol-b5699.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-AwaSv-9sGyranY9xR1OafLITiK0c6lA',
    appId: '1:1052600817177:ios:55c9a078c497cc1f073c88',
    messagingSenderId: '1052600817177',
    projectId: 'fanuccontrol-b5699',
    databaseURL: 'https://fanuccontrol-b5699-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fanuccontrol-b5699.firebasestorage.app',
    iosBundleId: 'com.example.fanucControl',
  );
}
